mocniak_bundle_test:
  path: /test
  defaults: { _controller: Mocniak\PropagandaBundle\Controller\DefaultController::testAction }

homepage:
  path: /
  defaults: { _controller: Mocniak\PropagandaBundle\Controller\DefaultController::indexAction }
