services:
  Mocniak\PropagandaBundle\Controller\DefaultController:
    public: true

  Aptoma\Twig\Extension\MarkdownEngine\ParsedownEngine:
    class: Aptoma\Twig\Extension\MarkdownEngine\ParsedownEngine

  propaganda.twig.markdown:
    class: Aptoma\Twig\Extension\MarkdownExtension
    arguments: ['@Aptoma\Twig\Extension\MarkdownEngine\ParsedownEngine']
    tags:
      - { name: twig.extension }